# Generated by Django 3.2.7 on 2022-02-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0003_resum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='resum',
        ),
    ]
