# Generated by Django 3.2.7 on 2022-02-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0006_resum_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resum',
            name='resume',
        ),
        migrations.AddField(
            model_name='skill',
            name='resume',
            field=models.FileField(default=1, upload_to='files'),
            preserve_default=False,
        ),
    ]
