# Generated by Django 3.2.7 on 2022-02-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0007_auto_20220224_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.RemoveField(
            model_name='resum',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='resum',
            name='whos',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='resume',
        ),
        migrations.AddField(
            model_name='resum',
            name='resume',
            field=models.FileField(default=1, upload_to='files'),
            preserve_default=False,
        ),
    ]
