# Generated by Django 3.2.7 on 2022-02-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0008_auto_20220224_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='who',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whos', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='pics')),
                ('resume', models.FileField(upload_to='files')),
            ],
        ),
        migrations.DeleteModel(
            name='photos',
        ),
        migrations.DeleteModel(
            name='resum',
        ),
        migrations.AddField(
            model_name='skill',
            name='photo',
            field=models.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='resume',
            field=models.FileField(default=1, upload_to='files'),
            preserve_default=False,
        ),
    ]
