# Generated by Django 3.2.7 on 2022-02-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0010_auto_20220224_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
