# Generated by Django 3.2.7 on 2022-02-24 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0011_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='photos',
        ),
    ]
